import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NoiseBg from "@/components/NoiseBg/NoiseBg";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

const messina = localFont({
  src: "../public/fonts/Messina.ttf",
  variable: "--messina",
  display: "swap",
});

const messinaCondensed = localFont({
  src: "../public/fonts/MessinaCondensed.ttf",
  variable: "--messinaCondensed",
  display: "swap",
});

const dashing = localFont({
  src: "../public/fonts/Dashing.otf",
  variable: "--dashing",
  display: "swap",
});

const dashingReg = localFont({
  src: "../public/fonts/DashingRegular.otf",
  variable: "--dashingReg",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${messinaCondensed.variable} ${messina.variable} ${dashing.variable} ${dashingReg.variable}`}
      >
        <Toaster
          position='top-center'
          toastOptions={{
            className: "toastFont",
            duration: 6000,
            style: {
              border: "2px solid #141e46",
              borderRadius: "50px",
              textAlign: "center",
              whiteSpace: "nowrap",
            },
          }}
        />
        <NoiseBg>{children}</NoiseBg>
      </body>
    </html>
  );
}
